version: "3"
services:
  master:
    build: ../docker-spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    networks:
        - spark-network
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 20002:20002
    volumes:
      - ./data:/tmp/data

  worker:
    build: ../docker-spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    networks:
        - spark-network
    ports:
      - 8081:8081
    volumes:
      - ./data:/tmp/data

  application:
    image: semantive/sbt-application:1.0
    links:
      - master
    networks:
        - spark-network

networks:
  spark-network:
    driver: bridge
